<?php


function extension_printfriendly_link($type, $object, $teaser = FALSE) {
  $links = array();
  $links['print-friendly'] = array(
    'title' => t('Print-friendly version'), 
    'href' => 'node/' . $object->nid . '/print', 
    'attributes' => array('title' => t('Show a printer-friendly version of this page')),
  );
  return($links);
}

function extension_printfriendly_preprocess_page(&$variables) {
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == 'print') {
    $variables['template_files'][] =  'page-print';
  }
}

function extension_printfriendly_theme_registry_alter(&$theme_registry) {
  $modulepath = drupal_get_path('module', 'extension_printfriendly') . '/theme';
  array_unshift($theme_registry['page']['theme paths'], $modulepath);
}